/**
 * /reset-password?token=<hex>
 *
 * Staff self-service password reset page.
 * Reached from the link generated by POST /api/v1/auth/forgot-password.
 */
import React, { useState } from 'react'
import { Link, useSearchParams, useNavigate } from 'react-router-dom'
import apiClient from '../api/client'

const ResetPassword: React.FC = () => {
  const [searchParams] = useSearchParams()
  const navigate = useNavigate()

  const token = searchParams.get('token') ?? ''

  const [newPassword, setNewPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [showPwd, setShowPwd] = useState(false)
  const [status, setStatus] = useState<'idle' | 'loading' | 'done' | 'error'>('idle')
  const [msg, setMsg] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!token) return setMsg('Reset token is missing from the URL.')

    if (newPassword.length < 8) return setMsg('Password must be at least 8 characters.')
    if (!/[A-Z]/.test(newPassword)) return setMsg('Password must contain at least one uppercase letter.')
    if (!/[0-9]/.test(newPassword)) return setMsg('Password must contain at least one number.')
    if (newPassword !== confirm) return setMsg('Passwords do not match.')

    setStatus('loading')
    setMsg('')

    try {
      const res = await apiClient.post('/v1/auth/reset-password', { token, newPassword })
      setMsg(res.data?.message ?? 'Password reset successful.')
      setStatus('done')
      // Redirect to login after 3 s
      setTimeout(() => navigate('/login', { replace: true }), 3000)
    } catch (err: unknown) {
      const apiMsg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
      setMsg(apiMsg || 'Reset failed. The link may have expired — please request a new one.')
      setStatus('error')
    }
  }

  return (
    <div
      className="min-h-screen flex flex-col relative"
      style={{ background: 'linear-gradient(135deg, #0b2545 0%, #1a3a5c 100%)' }}
    >
      {/* Navbar */}
      <nav className="w-full flex items-center gap-3 px-4 sm:px-6 py-3 shadow-sm relative z-40 bg-primary border-b border-white/10">
        <Link to="/" className="flex items-center gap-3">
          <img src="/assets/image.png" alt="SGSITS" className="w-10 h-10 object-contain bg-white rounded-full p-0.5 shrink-0" />
          <div className="hidden sm:block text-left">
            <p className="text-white font-bold text-sm leading-tight">Shri G. S. Institute</p>
            <p className="text-white/50 text-[11px]">of Technology and Science, Indore</p>
          </div>
        </Link>
        <div className="ml-auto">
          <Link to="/login" className="text-white/70 hover:text-white text-xs font-medium transition-colors">
            ← Back to Login
          </Link>
        </div>
      </nav>

      <div className="flex-1 flex items-center justify-center px-4 py-10 relative z-10">
        <div className="w-full max-w-[400px]">
          <div className="bg-white rounded-md shadow-sm border border-slate-200 overflow-hidden">
            <div className="h-1.5 bg-accent" />

            <div className="px-7 sm:px-9 py-8">
              <div className="flex flex-col items-center mb-6 text-center">
                <img src="/assets/image.png" alt="SGSITS" className="w-12 h-12 object-contain mb-3" />
                <h1 className="text-xl font-display font-bold text-gray-800">Set New Password</h1>
                <p className="text-xs text-slate-500 mt-0.5">Enter a new password for your SGSITS account</p>
              </div>

              {!token && (
                <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded px-4 py-3 mb-4">
                  Invalid reset link — the token is missing. Please request a new one from the{' '}
                  <Link to="/login" className="underline">login page</Link>.
                </div>
              )}

              {status === 'done' ? (
                <div className="text-sm text-green-700 bg-green-50 border border-green-200 rounded px-4 py-3">
                  {msg}
                  <p className="text-xs text-green-600 mt-1">Redirecting you to login…</p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-4" noValidate>
                  {msg && status === 'error' && (
                    <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded px-4 py-3">
                      {msg}
                    </div>
                  )}
                  {msg && status === 'idle' && (
                    <div className="text-sm text-yellow-700 bg-yellow-50 border border-yellow-200 rounded px-4 py-3">
                      {msg}
                    </div>
                  )}

                  <div>
                    <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wide block mb-1">
                      New Password
                    </label>
                    <div className="relative">
                      <input
                        type={showPwd ? 'text' : 'password'}
                        value={newPassword}
                        onChange={e => setNewPassword(e.target.value)}
                        placeholder="At least 8 chars, 1 uppercase, 1 number"
                        required
                        disabled={!token || status === 'loading'}
                        className="w-full border border-gray-300 rounded px-4 py-2.5 pr-11 text-sm focus:outline-none placeholder-gray-400 bg-white focus:border-primary disabled:opacity-60"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPwd(s => !s)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                      >
                        {showPwd ? '🙈' : '👁'}
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wide block mb-1">
                      Confirm Password
                    </label>
                    <input
                      type={showPwd ? 'text' : 'password'}
                      value={confirm}
                      onChange={e => setConfirm(e.target.value)}
                      placeholder="Re-enter your new password"
                      required
                      disabled={!token || status === 'loading'}
                      className="w-full border border-gray-300 rounded px-4 py-2.5 text-sm focus:outline-none placeholder-gray-400 bg-white focus:border-primary disabled:opacity-60"
                    />
                  </div>

                  <p className="text-[10px] text-slate-400">
                    Min 8 characters · At least one uppercase letter · At least one number
                  </p>

                  <button
                    type="submit"
                    disabled={!token || status === 'loading' || !newPassword || !confirm}
                    className="w-full py-3 rounded text-white font-bold text-sm bg-primary hover:opacity-95 disabled:opacity-50 transition-all"
                  >
                    {status === 'loading' ? 'Resetting…' : 'Reset Password'}
                  </button>
                </form>
              )}
            </div>
          </div>

          <p className="text-center text-white/60 text-xs mt-5">
            © {new Date().getFullYear()} SGSITS Indore. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  )
}

export default ResetPassword
