export interface SidebarLink {
  label: string
  path: string
}

export const sidebarLinks: Record<string, SidebarLink[]> = {
  about: [
    { label: 'About Institute', path: '/about/institute' },
    { label: 'Vision & Mission', path: '/about/vision-mission' },
    { label: "Director's Message", path: '/about/director-message' },
    { label: 'Governing Body', path: '/about/governing-body' },
    { label: 'Administration', path: '/about/administration' },
    { label: 'Administrative Committees', path: '/about/committees' },
    { label: 'Telephone Directory', path: '/about/telephone-directory' },
    { label: 'Infrastructure', path: '/about/infrastructure' },
    { label: 'IQAC Cell', path: '/about/iqac' },
    { label: 'Academic Council', path: '/about/academic-council' },
    { label: 'Accreditation (NBA/NAAC)', path: '/about/accreditation' },
  ],
  academics: [
    { label: 'Academic Calendar', path: '/academics/calendar' },
    { label: 'UG Courses', path: '/academics/courses/ug' },
    { label: 'PG Courses', path: '/academics/courses/pg' },
    { label: 'Ph.D. Programs', path: '/academics/courses/phd' },
    { label: 'PTDC Courses', path: '/academics/courses/ptdc' },
    { label: 'Online Courses (MOOC)', path: '/academics/courses/online' },
    { label: 'First Year Info', path: '/academics/first-year' },
    { label: 'Exam & Results', path: '/academics/exam-results' },
    { label: 'Ordinances', path: '/academics/ordinances' },
    { label: 'Plagiarism Policy', path: '/academics/plagiarism-policy' },
    { label: 'Code of Ethics', path: '/academics/code-of-conduct' },
    { label: 'OBE & NEP 2020', path: '/academics/obe-nep-2020' },
  ],
  admission: [
    { label: 'UG Admission', path: '/admission/ug' },
    { label: 'PG Admission', path: '/admission/pg' },
    { label: 'PhD Admission', path: '/admission/phd' },
    { label: 'Prospectus Download', path: '/admission/prospectus' },
  ],
  placement: [
    { label: 'T&P Cell Overview', path: '/placement/tnp-cell' },
    { label: 'Leading Recruiters', path: '/placement/companies' },
    { label: 'Placement Record', path: '/placement/record' },
    { label: 'Placement Contacts', path: '/placement/contact' },
  ],
  students: [
    { label: 'Student Activities', path: '/students/activities' },
    { label: 'Govt. Scholarships', path: '/students/scholarship/govt' },
    { label: 'Institute Scholarships', path: '/students/scholarship/institute' },
    { label: 'Sports & Games (SSS)', path: '/students/sss' },
    { label: 'NCC Wing', path: '/students/ncc' },
    { label: 'NSS Wing', path: '/students/nss' },
  ],
  facilities: [
    { label: 'Computer Center', path: '/facilities/computer-center' },
    { label: 'Central Library', path: '/facilities/library' },
    { label: 'Central Workshop', path: '/facilities/workshop' },
    { label: 'Gymnasium', path: '/facilities/gymnasium' },
    { label: 'Dispensary', path: '/facilities/dispensary' },
    { label: 'CIDI Center', path: '/facilities/cidi' },
    { label: 'Sports Complex', path: '/facilities/sports' },
    { label: 'Boys Hostel', path: '/facilities/hostel/boys' },
    { label: 'Girls Hostel', path: '/facilities/hostel/girls' },
    { label: 'Transit Hostel', path: '/facilities/hostel/transit' },
    { label: 'Staff Quarters', path: '/facilities/hostel/staff' },
    { label: 'AICTE IDEA Lab', path: '/facilities/idea-lab' },
  ],
  explore: [
    { label: 'Campus Map', path: '/explore/campus-map' },
    { label: 'Photo Gallery', path: '/explore/gallery' },
    { label: 'Video Tour', path: '/explore/video-tour' },
    { label: 'SGSITS Anthem', path: '/explore/anthem' },
  ],
  teqip: [
    { label: 'About TEQIP', path: '/teqip/about' },
    { label: 'Objectives', path: '/teqip/objectives' },
    { label: 'Financial Allocation', path: '/teqip/financial' },
    { label: 'Equity Action Plan', path: '/teqip/equity' },
    { label: 'Board of Governors', path: '/teqip/bog' },
    { label: 'Twinning Arrangement', path: '/teqip/twinning' },
    { label: 'Expenditures List', path: '/teqip/expenditures' },
    { label: 'Vouchers & Forms', path: '/teqip/vouchers' },
  ],
  news: [
    { label: 'Campus News', path: '/news' },
    { label: 'Latest Notices', path: '/notices' },
    { label: 'Upcoming Events', path: '/events' },
    { label: 'Active Tenders', path: '/tenders' },
  ],
  notices: [
    { label: 'Campus News', path: '/news' },
    { label: 'Latest Notices', path: '/notices' },
    { label: 'Upcoming Events', path: '/events' },
    { label: 'Active Tenders', path: '/tenders' },
  ],
  events: [
    { label: 'Campus News', path: '/news' },
    { label: 'Latest Notices', path: '/notices' },
    { label: 'Upcoming Events', path: '/events' },
    { label: 'Active Tenders', path: '/tenders' },
  ],
  tenders: [
    { label: 'Campus News', path: '/news' },
    { label: 'Latest Notices', path: '/notices' },
    { label: 'Upcoming Events', path: '/events' },
    { label: 'Active Tenders', path: '/tenders' },
  ]
}
